// src/pages/Stats.vue
<template>
  <a-row :gutter="16">
    <a-col :span="12">
      <a-card title="收支总览">
        <div ref="barChart" style="height: 300px"></div>
      </a-card>
    </a-col>
    <a-col :span="12">
      <a-card title="支出分类">
        <div ref="pieChart" style="height: 300px"></div>
      </a-card>
    </a-col>
  </a-row>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import * as echarts from 'echarts'
import dayjs from 'dayjs'

const api = (window as any).api
const barChart = ref<HTMLDivElement>()
const pieChart = ref<HTMLDivElement>()
let barInstance: echarts.ECharts | null = null
let pieInstance: echarts.ECharts | null = null

const loadStats = async () => {
  const month = dayjs().format('YYYY-MM')
  const stats = await api.getMonthlyStats(month)

  if (barInstance) {
    barInstance.setOption({
      tooltip: { trigger: 'axis' },
      xAxis: { type: 'category', data: ['收入', '支出', '净收入'] },
      yAxis: { type: 'value' },
      series: [{
        type: 'bar',
        data: [
          { value: stats.income, itemStyle: { color: '#3f8600' } },
          { value: stats.expense, itemStyle: { color: '#cf1322' } },
          { value: stats.income - stats.expense, itemStyle: { color: '#1890ff' } },
        ],
      }],
    })
  }

  if (pieInstance && stats.byCategory.length > 0) {
    pieInstance.setOption({
      tooltip: { trigger: 'item' },
      series: [{
        type: 'pie',
        radius: '60%',
        data: stats.byCategory.map((c: any) => ({ name: c.category, value: c.total })),
        emphasis: { itemStyle: { shadowBlur: 10, shadowColor: 'rgba(0,0,0,0.3)' } },
      }],
    })
  }
}

onMounted(() => {
  if (barChart.value) barInstance = echarts.init(barChart.value)
  if (pieChart.value) pieInstance = echarts.init(pieChart.value)
  loadStats()
})

onUnmounted(() => {
  barInstance?.dispose()
  pieInstance?.dispose()
})
</script>

// src/pages/Stats.tsx
import { useState, useEffect } from 'react'
import { Card, Row, Col, DatePicker, Empty } from 'antd'
import ReactECharts from 'echarts-for-react'
import dayjs from 'dayjs'

interface StatsData {
  income: number
  expense: number
  byCategory: { category: string; total: number }[]
}

export default function Stats() {
  const [month, setMonth] = useState(dayjs())
  const [stats, setStats] = useState<StatsData | null>(null)

  const loadStats = async () => {
    const data = await (window as any).api.getMonthlyStats(month.format('YYYY-MM'))
    setStats(data)
  }

  useEffect(() => { loadStats() }, [month])

  if (!stats) return null

  const hasData = stats.income > 0 || stats.expense > 0

  const pieOption = {
    tooltip: { trigger: 'item', formatter: '{b}: ¥{c} ({d}%)' },
    legend: { orient: 'vertical', left: 'left' },
    series: [
      {
        type: 'pie',
        radius: '60%',
        data: stats.byCategory.map((item) => ({
          name: item.category,
          value: item.total,
        })),
        emphasis: {
          itemStyle: { shadowBlur: 10, shadowOffsetX: 0, shadowColor: 'rgba(0, 0, 0, 0.5)' },
        },
      },
    ],
  }

  const barOption = {
    tooltip: { trigger: 'axis' },
    xAxis: {
      type: 'category',
      data: ['收入', '支出', '净收入'],
    },
    yAxis: { type: 'value', name: '金额 (元)' },
    series: [
      {
        type: 'bar',
        data: [
          { value: stats.income, itemStyle: { color: '#3f8600' } },
          { value: stats.expense, itemStyle: { color: '#cf1322' } },
          {
            value: stats.income - stats.expense,
            itemStyle: { color: stats.income - stats.expense >= 0 ? '#1677ff' : '#cf1322' },
          },
        ],
        label: {
          show: true,
          position: 'top',
          formatter: (p: any) => `¥${p.value.toFixed(2)}`,
        },
      },
    ],
  }

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        <DatePicker
          picker="month"
          value={month}
          onChange={(v) => v && setMonth(v)}
          allowClear={false}
        />
      </div>

      {!hasData ? (
        <Card><Empty description="本月暂无数据" /></Card>
      ) : (
        <Row gutter={16}>
          <Col span={12}>
            <Card title="收支概览">
              <ReactECharts option={barOption} style={{ height: 300 }} />
            </Card>
          </Col>
          <Col span={12}>
            <Card title="支出分类">
              {stats.byCategory.length > 0 ? (
                <ReactECharts option={pieOption} style={{ height: 300 }} />
              ) : (
                <Empty description="暂无支出数据" />
              )}
            </Card>
          </Col>
        </Row>
      )}
    </div>
  )
}
